version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24

  pre_build:
    commands:
      - echo Installing dependencies...
      - cd frontend-angular
      - npm install

  build:
    commands:
      - echo Building Angular application...
      - npm run build

artifacts:
  base-directory: dist/angular-starter/browser
  files:
    - '**/*'